version: '2'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  elasticsearch:
    image: elasticsearch:8.4.3
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
  redis_writer:
    build: ./redis
    image: redis_writer:latest
    container_name: redis_writer
    depends_on:
      - redis
  kafka_writer:
    build: ./kafka
    image: kafka_writer:latest
    container_name: kafka_writer
    depends_on:
      - redis
      - kafka
      - redis_writer
  elasticsearch_writer:
    build: ./elasticsearch
    image: elasticsearch_writer:latest
    container_name: elasticsearch_writer
    depends_on:
      - kafka
      - elasticsearch
      - kafka_writer